# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf5e16685a150f10182e23ccd30b5cd08a8b90f66f12f169f7bde23961d804f66b4503c71f996381c88f3a66f0d118d61503bcce3c9211aed42d0f113b115d95

test:
  secret_key_base: 7fb82d9884dcd2f0e62fd7bd58294c3e759d550652842f742052b65534de53baa4b95089754a8024c8af7208ffaf63d998d6d56de2fab481af02f772af4d83fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
